### ISSUE TITLE
Termite Colors

### ISSUE THREAD

**Issue by iiPlasma** [drewtempelmeyer/palenight.vim#1]
Hey! I love this vim theme and have been using it for awhile now, but I hate the way it looks with my terminal (Termite). Is there a Termite theme that uses the same color layout as this theme or could I have the colors for everything like the background, RBG colors, etc. so I could make my own theme. Thanks c:

**Comment by codyloyd** [comment]
the colors can be found in 
 this file: https://github.com/drewtempelmeyer/palenight.vim/blob/master/autoload/palenight.vim
