### ISSUE TITLE
Native Vim installation conflict

### ISSUE THREAD

**Issue by aminnairi** [drewtempelmeyer/palenight.vim#14]
Hi there, great theme!

I was using your theme on one of my project and I figured out I would use it on my own installation.

I already had a `~/.vimrc` file with all my preferences. But installing with the native Vim system is conflicting with the current userland settings. A bunch of errors appear like:

```console
$ vim something.txt
...
line  481:
E121: Undefined variable: s:green
E116: Invalid arguments for function <SNR>13_h
...
```

Here is the following installation process:

```console
$ git clone https://github.com/drewtempelmeyer/palenight.vim ~/.vim/pack/bundle/start/
```

What has solved my issue was to move my current preferences to make it look like it is also a Vim plugin like so:

```console
$ mkdir -p ~/.vim/pack/bundle/start/default/plugin
$ mv ~/.vimrc ~/.vim/pack/bundle/start/default/plugin/default.vim
```

First line is saying *create a directory `default` with its subdirectory `plugin` inside `~/.vim/pack/bundle/start`* (Where all Vim 8+ plugins live). The second line is saying *Move and rename my file `~/.vimrc` to the folder I just created*.

Maybe this has nothing to do with your plugin but I wanted to open this issue to first help other people encountering this issue and second maybe see if there is something we can do to solve this issue using the native Vim plugin installation system.

Thanks!

**Comment by lincoln-b** [comment]
Thanks for sharing! I had this problem as well and your fix worked.
