### ISSUE TITLE
Two CSS sections?

### ISSUE THREAD

**Issue by adrian5** [drewtempelmeyer/palenight.vim#21]
I was looking at the language specific color settings, and noticed that there are two ([1](https://github.com/drewtempelmeyer/palenight.vim/blob/master/colors/palenight.vim#L200-L219), [2](https://github.com/drewtempelmeyer/palenight.vim/blob/master/colors/palenight.vim#L388-L393)) CSS sections with slight overlap. Is this due to some quirk?

**Comment by drewtempelmeyer** [comment]
@adrian5 good catch! I'm going to begin cleaning up the colors and adding additional language support.
