### ISSUE TITLE
Add support for termdebug

### ISSUE THREAD

**Issue by AlxHnr** [drewtempelmeyer/palenight.vim#26]
Recent versions of Vim and Neovim ship termdebug, a plugin for integrating gdb. The default colors look off. The sign column contains breakpoints, while the blue line shows where the program is paused:

![palenight](https://user-images.githubusercontent.com/8235638/91655306-e9265000-eaaf-11ea-9150-b5b5e3e3dad0.png)

## Suggestion

Termdebug has only two highlighting groups:

```vim
call s:h("debugBreakpoint", { "fg": s:blue_purple })
call s:h("debugPC", { "bg": s:blue_purple, "fg": s:black })
```

![palenight-fixed](https://user-images.githubusercontent.com/8235638/91655307-ea577d00-eaaf-11ea-8bbe-a43d8ff2de4e.png)

**Comment by drewtempelmeyer** [comment]
Hi, @AlxHnr! Mind opening a pull request and I'll merge this in :ok_hand:
