### ISSUE TITLE
Undefined variable: s:white_mask_11

### ISSUE THREAD

**Issue by mervinjin** [drewtempelmeyer/palenight.vim#29]
I update to latest version, and error opening VIM: 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/49034188/92432877-08b72a00-f1ce-11ea-9316-3aa4aa6974ab.png">

**Comment by tamago324** [comment]
I'm sorry. It's my PR's fault.
I will correct it later. Please wait a minute.

**Comment by mervinjin** [comment]
🤔  It doesn't matter. It doesn't affect my use.

**Comment by vighd** [comment]
Thanks for the quick fix. :+1:
