### ISSUE TITLE
tmux support

### ISSUE THREAD

**Issue by ricvillagrana** [drewtempelmeyer/palenight.vim#9]
This colorscheme is the best, but in tmux it has doesn't look like in the normal terminal (doesn't look bad, but is different).

**Comment by drewtempelmeyer** [comment]
@ricvillagrana thanks for the kind comments!

You might need to update your `.tmux.conf` to something similar to https://github.com/tmux/tmux/issues/1246

For example, I have the following:

```
# Set term color properly
set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
```
